services:
  smtp-contact-api:
    build: .
    restart: unless-stopped
    env_file: .env
    expose:
      - "3001"
    networks:
      - helloworldnepal-net

networks:
  helloworldnepal-net:
    external: true
